"""catalogo medicamentos y administraciones

Revision ID: 06f561f2264e
Revises: d4b58d65e0df
Create Date: 2025-12-15 14:37:08.138987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f561f2264e'
down_revision = 'd4b58d65e0df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administraciones_medicamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registro_enfermeria_id', sa.Integer(), nullable=False),
    sa.Column('medicamento_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unidad', sa.String(length=50), nullable=True),
    sa.Column('via', sa.String(length=50), nullable=True),
    sa.Column('hora_administracion', sa.DateTime(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ordenes_medicas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medicamentos_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes_medicas', schema=None) as batch_op:
        batch_op.drop_column('medicamentos_json')

    op.drop_table('administraciones_medicamentos')
    # ### end Alembic commands ###
