"""Ajuste id HistoriaClinica para usar id Paciente

Revision ID: 1244ae70223e
Revises: d5d0aa69221f
Create Date: 2025-10-22 11:01:49.861335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1244ae70223e'
down_revision = 'd5d0aa69221f'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('historias_clinicas', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_historias_paciente_id', ['paciente_id'])
        batch_op.create_foreign_key('fk_historias_paciente_id', 'pacientes', ['id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historias_clinicas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
