"""Agregar antecedentes, riesgos y alergias

Revision ID: 1cfc4a7ac119
Revises: 2c725410eb0c
Create Date: 2026-01-13 16:26:12.758169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cfc4a7ac119'
down_revision = '2c725410eb0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historias_clinicas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('antecedentes_medicos', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('antecedentes_farmacologicos', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('antecedentes_quirurgicos', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('antecedentes_toxicos', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('antecedentes_alergicos', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('antecedentes_ginecobstetricos', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('riesgos_general', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('riesgo_caidas_dowton', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('riesgo_upp_braden', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('riesgos_evaluacion', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tiene_alergias', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('descripcion_alergias', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historias_clinicas', schema=None) as batch_op:
        batch_op.drop_column('descripcion_alergias')
        batch_op.drop_column('tiene_alergias')
        batch_op.drop_column('riesgos_evaluacion')
        batch_op.drop_column('riesgo_upp_braden')
        batch_op.drop_column('riesgo_caidas_dowton')
        batch_op.drop_column('riesgos_general')
        batch_op.drop_column('antecedentes_ginecobstetricos')
        batch_op.drop_column('antecedentes_alergicos')
        batch_op.drop_column('antecedentes_toxicos')
        batch_op.drop_column('antecedentes_quirurgicos')
        batch_op.drop_column('antecedentes_farmacologicos')
        batch_op.drop_column('antecedentes_medicos')

    # ### end Alembic commands ###
