"""add servicio to historias_clinicas

Revision ID: 224fbc70290d
Revises: f395f6c0aa0c
Create Date: 2025-12-05 10:50:26.093730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224fbc70290d'
down_revision = 'f395f6c0aa0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historias_clinicas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servicio', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historias_clinicas', schema=None) as batch_op:
        batch_op.drop_column('servicio')

    # ### end Alembic commands ###
