"""Añadir fecha_registro a ordenes_medicas

Revision ID: 29a40a2014f8
Revises: 1cfc4a7ac119
Create Date: 2026-01-22 10:17:21.779538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a40a2014f8'
down_revision = '1cfc4a7ac119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes_medicas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes_medicas', schema=None) as batch_op:
        batch_op.drop_column('fecha_registro')

    # ### end Alembic commands ###
