"""orden laboratorio items

Revision ID: 2c725410eb0c
Revises: d11c019fa7df
Create Date: 2026-01-06 12:17:28.202406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c725410eb0c'
down_revision = 'd11c019fa7df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orden_laboratorio_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('examen_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['examen_id'], ['cat_laboratorio_examen.id'], ),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_medicas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orden_laboratorio_items')
    # ### end Alembic commands ###
