"""Add fecha_registro column to historias_clinicas

Revision ID: 3746cca11570
Revises: 4222f2078a48
Create Date: 2025-09-25 10:25:35.604387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3746cca11570'
down_revision = '4222f2078a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historias_clinicas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historias_clinicas', schema=None) as batch_op:
        batch_op.drop_column('fecha_registro')

    # ### end Alembic commands ###
