"""Initial migration with historias clinicas y ordenes medicas

Revision ID: 4222f2078a48
Revises: 
Create Date: 2025-09-24 12:02:14.116537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4222f2078a48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cie10',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('medicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('especialidad', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('cama', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('historias_clinicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_historia', sa.String(length=50), nullable=False),
    sa.Column('historia_base_id', sa.Integer(), nullable=True),
    sa.Column('numero_historia', sa.String(length=50), nullable=True),
    sa.Column('numero_ingreso', sa.String(length=50), nullable=True),
    sa.Column('nombre_paciente', sa.String(length=200), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('direccion', sa.String(length=250), nullable=True),
    sa.Column('procedencia', sa.String(length=250), nullable=True),
    sa.Column('sexo', sa.String(length=20), nullable=True),
    sa.Column('ocupacion', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('regimen', sa.String(length=50), nullable=True),
    sa.Column('estrato', sa.Integer(), nullable=True),
    sa.Column('plan_beneficios', sa.String(length=150), nullable=True),
    sa.Column('acudiente_responsable', sa.String(length=150), nullable=True),
    sa.Column('telefono_responsable', sa.String(length=50), nullable=True),
    sa.Column('direccion_responsable', sa.String(length=250), nullable=True),
    sa.Column('nombre_padre', sa.String(length=150), nullable=True),
    sa.Column('nombre_madre', sa.String(length=150), nullable=True),
    sa.Column('indicaciones_medicas_ordenes', sa.Text(), nullable=True),
    sa.Column('medicacion_texto', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['historia_base_id'], ['historias_clinicas.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registro_enfermeria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('signos_vitales', sa.String(length=255), nullable=True),
    sa.Column('balance_liquidos', sa.Float(), nullable=True),
    sa.Column('control_glicemia', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnosticos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('historia_id', sa.Integer(), nullable=False),
    sa.Column('cie10_codigo', sa.String(length=10), nullable=True),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['historia_id'], ['historias_clinicas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evoluciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('historia_id', sa.Integer(), nullable=False),
    sa.Column('subjetivos', sa.Text(), nullable=True),
    sa.Column('objetivos', sa.Text(), nullable=True),
    sa.Column('analisis', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('indicaciones_medicas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['historia_id'], ['historias_clinicas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordenes_medicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('historia_id', sa.Integer(), nullable=False),
    sa.Column('indicaciones_medicas', sa.Text(), nullable=True),
    sa.Column('medicacion_texto', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['historia_id'], ['historias_clinicas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signos_vitales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('historia_id', sa.Integer(), nullable=False),
    sa.Column('tension_arterial', sa.String(length=20), nullable=True),
    sa.Column('frecuencia_cardiaca', sa.String(length=20), nullable=True),
    sa.Column('frecuencia_respiratoria', sa.String(length=20), nullable=True),
    sa.Column('temperatura', sa.String(length=20), nullable=True),
    sa.Column('saturometria', sa.String(length=10), nullable=True),
    sa.Column('escala_dolor', sa.String(length=10), nullable=True),
    sa.Column('fi02', sa.String(length=10), nullable=True),
    sa.Column('estado_consciencia', sa.String(length=100), nullable=True),
    sa.Column('glucometria', sa.String(length=20), nullable=True),
    sa.Column('peso', sa.String(length=20), nullable=True),
    sa.Column('talla', sa.String(length=20), nullable=True),
    sa.Column('imc', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['historia_id'], ['historias_clinicas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signos_vitales')
    op.drop_table('ordenes_medicas')
    op.drop_table('evoluciones')
    op.drop_table('diagnosticos')
    op.drop_table('registro_enfermeria')
    op.drop_table('historias_clinicas')
    op.drop_table('usuarios')
    op.drop_table('pacientes')
    op.drop_table('medicos')
    op.drop_table('cie10')
    # ### end Alembic commands ###
