"""Add cantidad_usada to InsumoPaciente

Revision ID: 5072259d8b0b
Revises: 34b17c40e710
Create Date: 2026-01-02 10:33:55.712468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5072259d8b0b'
down_revision = '34b17c40e710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insumos_paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad_usada', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fecha_uso', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insumos_paciente', schema=None) as batch_op:
        batch_op.drop_column('fecha_uso')
        batch_op.drop_column('cantidad_usada')

    # ### end Alembic commands ###
