"""tabla diagnosticos CIE10

Revision ID: 5a5bd0b2749a
Revises: e86fc55ca165
Create Date: 2025-12-15 10:17:55.084855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a5bd0b2749a'
down_revision = 'e86fc55ca165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosticos_cie10', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('habilitado', sa.Boolean(), nullable=True))
        batch_op.alter_column('descripcion',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_diagnosticos_cie10_codigo'), ['codigo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosticos_cie10', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnosticos_cie10_codigo'))
        batch_op.alter_column('descripcion',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('habilitado')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
