"""add ayuda_diagnostica

Revision ID: 5fd32c7851d3
Revises: 224fbc70290d
Create Date: 2025-12-05 14:22:10.814968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd32c7851d3'
down_revision = '224fbc70290d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ayuda_diagnostica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('historia_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('nombre_examen', sa.String(length=255), nullable=False),
    sa.Column('fecha_resultado', sa.DateTime(), nullable=True),
    sa.Column('archivo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['historia_id'], ['historias_clinicas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ayuda_diagnostica')
    # ### end Alembic commands ###
