"""Add indicaciones_medicas and medicacion_texto to historias_clinicas

Revision ID: 711137b8a6f9
Revises: b5cea64a3e87
Create Date: 2025-09-30 15:01:03.452303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711137b8a6f9'
down_revision = 'b5cea64a3e87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historias_clinicas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('indicaciones_medicas', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historias_clinicas', schema=None) as batch_op:
        batch_op.drop_column('indicaciones_medicas')

    # ### end Alembic commands ###
