"""add campos evaluacion clinica

Revision ID: 8ab8cba60ffa
Revises: 1244ae70223e
Create Date: 2025-10-23 15:30:15.464691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab8cba60ffa'
down_revision = '1244ae70223e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historias_clinicas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subjetivos', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('objetivos', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('analisis', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('plan', sa.Text(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_historias_paciente_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_historias_paciente_id'), type_='foreignkey')
        batch_op.drop_column('fecha_ingreso')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historias_clinicas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_ingreso', sa.DATE(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_historias_paciente_id'), 'pacientes', ['id'], ['id'])
        batch_op.create_unique_constraint(batch_op.f('uq_historias_paciente_id'), ['paciente_id'])
        batch_op.drop_column('plan')
        batch_op.drop_column('analisis')
        batch_op.drop_column('objetivos')
        batch_op.drop_column('subjetivos')

    # ### end Alembic commands ###
