"""add stock_actual insumos_paciente

Revision ID: 8bd464bfa11e
Revises: 5072259d8b0b
Create Date: 2026-01-02 11:05:40.357290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd464bfa11e'
down_revision = '5072259d8b0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insumos_paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_actual', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insumos_paciente', schema=None) as batch_op:
        batch_op.drop_column('stock_actual')

    # ### end Alembic commands ###
