"""add turno to registro_enfermeria

Revision ID: a073cafc6477
Revises: b8102cfd5c95
Create Date: 2025-12-26 10:39:18.924498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a073cafc6477'
down_revision = 'b8102cfd5c95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_enfermeria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('turno', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_enfermeria', schema=None) as batch_op:
        batch_op.drop_column('turno')

    # ### end Alembic commands ###
