"""Agregar insumos médicos enfermería

Revision ID: acecab6b1aae
Revises: a073cafc6477
Create Date: 2025-12-30 10:06:30.201456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acecab6b1aae'
down_revision = 'a073cafc6477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insumos_medicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('stock_actual', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unidad', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insumos_medicos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insumos_medicos_codigo'), ['codigo'], unique=True)

    op.create_table('solicitudes_insumos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('insumo_medico_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unidad', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('enfermero_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['enfermero_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['insumo_medico_id'], ['insumos_medicos.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitudes_insumos')
    with op.batch_alter_table('insumos_medicos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insumos_medicos_codigo'))

    op.drop_table('insumos_medicos')
    # ### end Alembic commands ###
