"""add administracion_medicamento table

Revision ID: b8102cfd5c95
Revises: 06f561f2264e
Create Date: 2025-12-17 15:30:22.220379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8102cfd5c95'
down_revision = '06f561f2264e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administracion_medicamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registro_enfermeria_id', sa.Integer(), nullable=False),
    sa.Column('medicamento_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unidad', sa.String(length=50), nullable=True),
    sa.Column('via', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.Column('hora_administracion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamentos.id'], ),
    sa.ForeignKeyConstraint(['registro_enfermeria_id'], ['registro_enfermeria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('administraciones_medicamentos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administraciones_medicamentos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('registro_enfermeria_id', sa.INTEGER(), nullable=False),
    sa.Column('medicamento_id', sa.INTEGER(), nullable=False),
    sa.Column('cantidad', sa.NUMERIC(precision=12, scale=3), nullable=False),
    sa.Column('unidad', sa.VARCHAR(length=50), nullable=True),
    sa.Column('via', sa.VARCHAR(length=50), nullable=True),
    sa.Column('hora_administracion', sa.DATETIME(), nullable=False),
    sa.Column('observaciones', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('administracion_medicamento')
    # ### end Alembic commands ###
