"""add laboratorio_nombre and interpretacion

Revision ID: bdf65cb803cf
Revises: f7ba92bbb124
Create Date: 2025-12-10 12:08:29.253445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdf65cb803cf'
down_revision = 'f7ba92bbb124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_resultado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interpretacion', sa.String(length=255), nullable=True))

    with op.batch_alter_table('lab_solicitud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('laboratorio_nombre', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_solicitud', schema=None) as batch_op:
        batch_op.drop_column('laboratorio_nombre')

    with op.batch_alter_table('lab_resultado', schema=None) as batch_op:
        batch_op.drop_column('interpretacion')

    # ### end Alembic commands ###
