"""add observaciones to ayudas

Revision ID: c5d035dadf8c
Revises: 5fd32c7851d3
Create Date: 2025-12-05 15:34:34.740018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d035dadf8c'
down_revision = '5fd32c7851d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ayuda_diagnostica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observaciones', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ayuda_diagnostica', schema=None) as batch_op:
        batch_op.drop_column('observaciones')

    # ### end Alembic commands ###
