"""Add observaciones to InsumoPaciente

Revision ID: d11c019fa7df
Revises: 8bd464bfa11e
Create Date: 2026-01-05 09:19:32.642005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd11c019fa7df'
down_revision = '8bd464bfa11e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insumos_paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observaciones', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insumos_paciente', schema=None) as batch_op:
        batch_op.drop_column('observaciones')

    # ### end Alembic commands ###
