"""tabla medicamentos con inventario

Revision ID: d4b58d65e0df
Revises: 5a5bd0b2749a
Create Date: 2025-12-15 12:33:15.968115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b58d65e0df'
down_revision = '5a5bd0b2749a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forma_farmaceutica', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('presentacion', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cantidad_disponible', sa.Numeric(precision=12, scale=3), nullable=True))
        batch_op.add_column(sa.Column('unidad_inventario', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_medicamentos_codigo'), ['codigo'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicamentos_codigo'))
        batch_op.drop_column('unidad_inventario')
        batch_op.drop_column('cantidad_disponible')
        batch_op.drop_column('presentacion')
        batch_op.drop_column('forma_farmaceutica')

    # ### end Alembic commands ###
