"""Agregar campo fecha_ingreso

Revision ID: d5d0aa69221f
Revises: 711137b8a6f9
Create Date: 2025-10-17 15:24:18.964256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5d0aa69221f'
down_revision = '711137b8a6f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historias_clinicas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_ingreso', sa.Date(), nullable=True))
        batch_op.drop_column('indicaciones_medicas')
        batch_op.drop_column('medicacion_texto')
        batch_op.drop_column('indicaciones_medicas_ordenes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historias_clinicas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('indicaciones_medicas_ordenes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('medicacion_texto', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('indicaciones_medicas', sa.TEXT(), nullable=True))
        batch_op.drop_column('fecha_ingreso')

    # ### end Alembic commands ###
