"""Add nullable=False to historia_id in ordenes_medicas

Revision ID: d62fbdee40c2
Revises: 3746cca11570
Create Date: 2025-09-25 11:34:24.914775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd62fbdee40c2'
down_revision = '3746cca11570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historias_clinicas', schema=None) as batch_op:
        batch_op.drop_column('fecha_registro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historias_clinicas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
