"""empty message

Revision ID: de3ca7c49147
Revises: 29a40a2014f8
Create Date: 2026-03-24 16:00:00.950456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de3ca7c49147'
down_revision = '29a40a2014f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insumos_paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enfermero_id', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insumos_paciente', schema=None) as batch_op:
        batch_op.drop_column('enfermero_id')

    # ### end Alembic commands ###
