"""add cie10_principal servicio_hospitalario medicamentos_json

Revision ID: e86fc55ca165
Revises: def9d863c34c
Create Date: 2025-12-15 10:01:29.412688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86fc55ca165'
down_revision = 'def9d863c34c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnosticos_cie10',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('medicamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.drop_table('_alembic_tmp_cat_laboratorio_examen')
    with op.batch_alter_table('cat_laboratorio_examen', schema=None) as batch_op:
        batch_op.alter_column('grupo',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('activo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('historias_clinicas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cie10_principal', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('servicio_hospitalario', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('medicamentos_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historias_clinicas', schema=None) as batch_op:
        batch_op.drop_column('medicamentos_json')
        batch_op.drop_column('servicio_hospitalario')
        batch_op.drop_column('cie10_principal')

    with op.batch_alter_table('cat_laboratorio_examen', schema=None) as batch_op:
        batch_op.alter_column('activo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('grupo',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    op.create_table('_alembic_tmp_cat_laboratorio_examen',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=255), nullable=False),
    sa.Column('grupo', sa.VARCHAR(length=255), nullable=True),
    sa.Column('activo', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('medicamentos')
    op.drop_table('diagnosticos_cie10')
    # ### end Alembic commands ###
