"""add campos tipo_nota y texto_nota a registro_enfermeria

Revision ID: f395f6c0aa0c
Revises: ccad232b2b80
Create Date: 2025-12-01 17:04:51.195593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f395f6c0aa0c'
down_revision = 'ccad232b2b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_enfermeria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_nota', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('texto_nota', sa.Text(), nullable=True))
        batch_op.alter_column('signos_vitales',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('balance_liquidos',
               existing_type=sa.FLOAT(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('control_glicemia',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_enfermeria', schema=None) as batch_op:
        batch_op.alter_column('control_glicemia',
               existing_type=sa.String(length=50),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('balance_liquidos',
               existing_type=sa.Text(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('signos_vitales',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('texto_nota')
        batch_op.drop_column('tipo_nota')

    # ### end Alembic commands ###
