"""add lab models

Revision ID: f7ba92bbb124
Revises: c5d035dadf8c
Create Date: 2025-12-09 14:58:28.791692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ba92bbb124'
down_revision = 'c5d035dadf8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cat_laboratorio_examen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('grupo', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cat_laboratorio_parametro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('examen_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('unidad', sa.String(length=50), nullable=True),
    sa.Column('valor_ref_min', sa.Float(), nullable=True),
    sa.Column('valor_ref_max', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['examen_id'], ['cat_laboratorio_examen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_solicitud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('historia_id', sa.Integer(), nullable=False),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=False),
    sa.Column('fecha_muestra', sa.DateTime(), nullable=True),
    sa.Column('fecha_resultado', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['historia_id'], ['historias_clinicas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_resultado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('examen_id', sa.Integer(), nullable=False),
    sa.Column('parametro_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.String(length=100), nullable=True),
    sa.Column('unidad', sa.String(length=50), nullable=True),
    sa.Column('flag_fuera_rango', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['examen_id'], ['cat_laboratorio_examen.id'], ),
    sa.ForeignKeyConstraint(['parametro_id'], ['cat_laboratorio_parametro.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['lab_solicitud.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lab_resultado')
    op.drop_table('lab_solicitud')
    op.drop_table('cat_laboratorio_parametro')
    op.drop_table('cat_laboratorio_examen')
    # ### end Alembic commands ###
